import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import Splash from './Splash';
import registerServiceWorker from './registerServiceWorker';
// import 'semantic-ui-css/semantic.min.css';
// ReactDOM.render(<App />, document.getElementById('root'));
ReactDOM.render(<Splash />, document.getElementById('root'));
registerServiceWorker();
